Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,28 +1,57 @@
 version: 0.2
-  
+
 phases:
   install:
     runtime-versions:
+      python: 3.9
       java: corretto17
     commands:
-      - echo Updating apt-get
-      - apt-get update
-      - echo Installing Maven
-      - apt-get install -y maven
+      - "echo Checking for the latest repos to build project"
+      - "pip install requests"
+      - "python check_latest_commit.py"
+      - "export CONTENT=$(cat out.txt)"
+      - "echo Content of out.txt: $CONTENT"
+      - "mkdir -p artifact_output"
+      - "touch artifact_output/.keep"
+
   pre_build:
     commands:
-      - echo Pre-build phase started on date
-      - mvn --version
+      - echo "Pre-build phase started on date"
+      - |
+        if [ "$CONTENT" = "backend" ]; then
+          echo "Updating apt-get"
+          apt-get update
+          echo "Installing Maven"
+          apt-get install -y maven
+        else
+          echo "No backend update detected. Skipping pre-build and exiting..."
+          exit 0
+        fi
+
   build:
     commands:
-      - echo Build started on date
-      - echo Building the Maven project...
-      - mvn clean install
+      - |
+        if [ "$CONTENT" = "backend" ]; then
+          echo "Build started on date"
+          echo "Building the Maven project..."
+          mvn clean install
+        else
+          echo "No backend update detected. Skipping build and exiting..."
+          exit 0
+        fi
+        
   post_build:
     commands:
-      - echo Post-build phase started on date
-      - echo test comment
+      - echo "Post-build phase started on date"
+      - |
+        if [ "$CONTENT" = "backend" ]; then
+          echo "Attempting to upload artifacts..."
+          cp target/*.war artifact_output/ || echo "Artifact copy failed, continuing..."
+        else
+          echo "No artifacts to upload, skipping..."
+        fi
+
 artifacts:
   files:
-    - target/*.war
+    - "artifact_output/**/*"
   discard-paths: yes
